/*
 * UFPumpController.h
 *
 * Created: 11/5/2014 3:40:49 PM
 *  Author: user
 */ 


#ifndef UFPUMPCONTROLLER_H_
#define UFPUMPCONTROLLER_H_


typedef enum {
	
	CL_UF_STATE_IDLE,
	CL_UF_STATE_STARTED,
	CL_UF_STATE_STOPPED,
	CL_UF_STATE_PAUSED,
	CL_UF_STATE_COMPLETED,
	CL_UF_STATE_MAXSTATE
	
}cl_uf_states;
typedef enum {
	
	CL_UF_EVENT_NULL,
	CL_UF_EVENT_SET_UF_RATE,
	CL_UF_EVENT_START,
	CL_UF_EVENT_PAUSE,
	CL_UF_EVENT_STOP,
	CL_UF_EVENT_COMPLETED,
	CL_UF_EVENT_SECOND,
	CL_UF_EVENT_MAX_EVENT
}cl_uf_events;




#endif /* UFPUMPCONTROLLER_H_ */