/*
 * cl_consolecontroller.h
 *
 * Created: 12/27/2013 5:22:45 PM
 *  Author: user
 */ 


#ifndef CL_CONSOLEHANDLER_H_
#define CL_CONSOLEHANDLER_H_

#define CL_CONSOLEMSG_STARTBYTE1 204 // 0xCC 
#define CL_CONSOLEMSG_STARTBYTE2 221 //0xDD
#define CL_CONSOLEMSG_STOPBYTE1	 238 //0xEE
#define CL_CONSOLEMSG_STOPBYTE2  187 //0XBB

typedef enum {	
			 MSG_RX_IDLE,
			 MSG_RX_WAITING_FOR_START,
			 MSG_RX_START_RECEIVED,
             MSG_RX_MESSAGE_CONFIRMED,
	
	}Cl_ConsoleMsg_readStateType;
	
	typedef enum {
		
			CON_STATE_IDLE,
			CON_STATE_INIT,
			CON_STATE_ACTIVE,
			CON_STATE_MAX
		}Cl_Cl_ConsoleStateType;

	typedef enum {
		CON_SYNC_STATE_WAIT_FOR_SYNC,
		CON_SYNC_STATE_SYNC_RECVD,
		CON_SYNC_STATE_WAIT_FOR_SYNC_ACK,
		CON_SYNC_STATE_SYNC_ACK_RECVD,
		CON_SYNC_STATE_MAX
	}Cl_ConsoleSyncStatesType;
	


		
typedef enum {
			CON_RX_COMMAND_VOID,
			CON_RX_COMMAND_SYNC = 03,
			CON_RX_COMMAND_ACK,//04
			CON_RX_COMMAND_RINSE_START,//05
			CON_RX_COMMAND_RINSE_PAUSE,//06
			CON_RX_COMMAND_RINSE_STOP,//07
			CON_RX_COMMAND_DIALYSIS_PREP,//08
			CON_RX_COMMAND_SET_DATA,//09
			CON_RX_COMMAND_GET_DATA,//0A
			CON_RX_COMMAND_SET_BLDPMP_ON,//0B
			CON_RX_COMMAND_SET_BLDPMP_OFF,//0C
			CON_RX_COMMAND_SET_BLDPUMPRATE,//0D
			CON_RX_COMMAND_START_PRIME,//0E
			CON_RX_COMMAND_START_DIALISER_PRIME,//0F
			CON_RX_COMMAND_HEP_PMP_SET,//10
			CON_RX_COMMAND_MAN_PREP_COMPLETED,//11
			CON_RX_COMMAND_DIALYSIS_START,//12
			CON_RX_COMMAND_DIALYSIS_STOP,//13
			CON_RX_COMMAND_DIALYSIS_PAUSE,//14
			CON_RX_COMMAND_CLR_ALARM,//15
			CON_RX_COMMAND_MUTE,//16
			CON_RX_COMMAND_TEST_HARNESS,//17
			CON_RX_COMMAND_START_DIALYSATE_FILL,//18
			CON_RX_COMMAND_STOP_PRIME, //19
			CON_RX_COMMAND_USER_MODE_ENTER,//1A
			CON_RX_COMMAND_USER_MODE_EXIT,//1B
			CON_RX_COMMAND_SERVICEMODE_ENTER,//1C
			CON_RX_COMMAND_SERVICEMODE_EXIT,//1D
			CON_RX_COMMAND_DIALYSER_CONNECTED,//1E
			CON_RX_EVT_COMMAND_PATIENT_CONNECTED,//1F
			CON_RX_EVT_COMMAND_STOP_DIALYSER_PRIME,//20
			CON_RX_EVT_COMMAND_MIXING_PREP_START,//0x21
			CON_RX_EVT_COMMAND_MIXING_PREP_STOP,//0x22
			CON_RX_EVT_COMMAND_RCIRC_START,//0x23
			CON_RX_EVT_COMMAND_RCIRC_STOP,//0x24
			CON_RX_EVT_COMMAND_START_RETURN , // 0x25 37,
			CON_RX_EVT_COMMAND_STOP_RETURN, //0x6  38,
			CON_RX_EVT_COMMAND_BYPASS_ON , // 0x27  39,
			CON_RX_EVT_COMMAND_BYPASS_OFF , //0x28  40,
			CON_RX_EVT_COMMAND_MINUF_ON,  //0x29  41,
			CON_RX_EVT_COMMAND_MINUF_OFF, // 0x2A = 42,
			CON_RX_EVT_COMMAND_PATIENT_READY, // 0x2B 43;
			CON_RX_EVT_COMMAND_START_DISINF, //0x2C 44
			CON_RX_EVT_COMMAND_STOP_DISINF, // 0x2D 45
			CON_RX_EVT_COMMAND_DUMMY_46,	//0x2E 46
			CON_RX_EVT_COMMAND_RESUME_DISINF_STAGE, //0x2f 47
			CON_RX_COMMAND_DIALYSIS_VPT_APT_DEFAULT_ALARM_WINDOW,//0x30 48

			CON_RX_COMMANDMAX// 0x30 48
		} Cl_ConsoleRxEventsType;

typedef enum{
			CON_TX_COMMAND_VOID,
			CON_TX_COMMAND_SYNC = 03,
			CON_TX_COMMAND_ACK , //0x04
			CON_TX_COMMAND_MODE, //05
			CON_TX_COMMAND_SYSINFO,//06
			CON_TX_COMMAND_ALARM,//07
			CON_TX_COMMAND_RINSE_CONFIRM,//08
			CON_TX_COMMAND_RINSE_STARTED,//09
			CON_TX_COMMAND_REM_TIME,//0A
			CON_TX_COMMAND_RINSE_COMPLETED,//0B
			CON_TX_COMMAND_DLSIS_PREP_CNFRM,//0C
			CON_TX_COMMAND_START_PRIME_CNFRM,//0D
			CON_TX_COMMAND_START_DIALISER_PRIME_CNFRM,//0E
			CON_TX_COMMAND_PRIME_COMPLETED,//0F
			CON_TX_COMMAND_DIALISYS_PRIME_COMPLETED,//10
			CON_TX_COMMAND_DLSIS_MAN_PREP_CMPLTD,//11
			CON_TX_COMMAND_DLSIS_CNFRM,//12
			CON_TX_COMMAND_DLSIS_STARTED,//13
			CON_TX_COMMAND_DLSIS_STOPPED,//14
			CON_TX_COMMAND_DIALYS_COMPLTED,//15
			CON_TX_COMMAND_SYSDATA,//0x16
			CON_TX_COMMAND_TEST_SYSDATA,//0x17
			CON_TX_COMMAND_PRINTTEXT, //0x18
			CON_TX_COMMAND_PRINTDATA, //0x19   25
			CON_TX_COMMAND_INIT_STATE, //0x1A  26
			CON_TX_COMMAND_INIT_DONE,//0x1B   27
			CON_TX_COMMAND_TICK_SEC, //0x1C 28
			CON_TX_COMMAND_DIALYSATE_FILLING_CONFIRM,//0x1D 29
			CON_TX_COMMAND_DIALYSATE_FILLING_STARTED,//0x1E 30
			CON_TX_COMMAND_DIALYSATE_FILLING_COMPLETED, //0x1F 31
			CON_TX_COMMAND_DIALYSATE_FILLING_TIMEOUT, // 0X20 32
			CON_TX_COMMAND_SYS_VERSION, //0x21 33
			CON_TX_COMMAND_RINSE_STOPPED, // 0x22 34
			CON_TX_COMMAND_PRIME_STOPPED, //0x23 35
			CON_TX_COMMAND_PRIME_STARTED,//0x24 36
			CON_TX_COMMAND_DIALYSER_CONNECTED_CONFIRMED,//0x25  37
			CON_TX_COMMAND_PATIENT_CONNECTED_CONFIRMED,//0x26  38
			CON_TX_COMMAND_BLOOD_DETECTED,//0x27  39
			CON_TX_COMMAND_DIALYSER_PRIME_STARTED, //0x28 //40
			CON_TX_COMMAND_DIALYSER_PRIME_STOPPED, //0x29 //41
			CON_TX_COMMAND_SYS_STATE_DATA, //0x2A //42
			CON_TX_COMMAND_SYS_STATE,//0x2B //43
			CON_TX_COMMAND_SYS_DUMMY_44, //0x2C
			CON_TX_COMMAND_DIALYSATE_FILLING_STOPPED, //0x2D //45
			CON_TX_COMMAND_SYS_DUMMY_46,//0x2E
			CONT_TX_COMMAND_SYS_RCIRC_STARTED,//0x2F 47
			CONT_TX_COMMAND_SYS_RCIRC_STOPPED,//0x30 48
			CONT_TX_COMMAND_SYS_RCIRC_COMPLETED,// 0X31 49
			CONT_TX_COMMAND_SYS_RET_STARTED,//0X32 50
			CONT_TX_COMMAND_SYS_RET_STOPPED,//0X33 51
			CONT_TX_COMMAND_SYS_RET_COMPLETED,//0X34 52
			CONT_TX_COMMAND_BLOODPUMP_ON,//0X35 53
			CONT_TX_COMMAND_BLOODPUMP_OFF,//0X36 54
			CON_TX_COMMAND_COMMAND_SCRIPT_PRNIT, //0X37 55
			CON_TX_COMMAND_DISINF_PAUSED, //0X38 56
			CON_TX_COMMAND_DISINF_STAGE_COMPLETED,//0X39 57
			CON_TX_COMMAND_DISINF_COMPLETED, //0X3A 58
			CON_TX_COMMAND_DISINF_RESUMED, //0X3B 59
			CON_TX_COMMAND_DISINF_STARTED,//0X3C 60
			CON_TX_COMMAND_COMMAND_IIC_HANGUP,//0X3D 61
			CON_TX_COMMAND_COMMAND_SCRIPT_BULK_PRINT,//0X3E 62
			CON_TX_COMMAND_DISINF_CONFIRM,//0X3F 63
			CON_TX_COMMAND_DLSIS_PAUSED,//0X40 64
			CON_TX_COMMAND_DLSIS_BYPASS_ON, //0x41 65
			CON_TX_COMMAND_DLSIS_BYPASS_OFF, //0x42 66
			CON_TX_COMMAND_DLSIS_RESUMED, //0x43 67
			CON_TX_COMMAND_COMMAND_HEATER_STATE, //0X44 67
			CON_TX_COMMAND_COMMAND_SYSTEM_STATE, //0X45 68
			CON_TX_COMMAND_COMMAND_SUBSYSTEM_STATE, //0X46 68
			CON_TX_COMMAND_COMMAND_SYSTEM_STATUS, //0x47 69
			CON_TX_COMMAND_COMMAND_ALARM_STATUS,//0x48 70
			CON_TX_COMMAND_COMMAND_MAX//
		}Cl_ConsoleTxCommandtype;
		
		
typedef enum {
	CON_RX_PARAM_DATA_NULL, // 0x00
	CON_RX_PARAM_DATA_RINSE_STATUS,//0x01
	CON_RX_PARAM_DATA_PRIME_STATUS, //0x02
	CON_RX_PARAM_DATA_DIALYSER_PRIME_STATUS,//0x03
	CON_RX_PARAM_DATA_DIALYSIS_STATUS,//0x04
	CON_RX_PARAM_DATA_DIALYSIS_FLOW,//0x05
	CON_RX_PARAM_DATA_DIALYSIS_TEMP,//0x06
	CON_RX_PARAM_DATA_HEPARIN_RATE,//0x07
	CON_RX_PARAM_DATA_APT_VALUE,//0x08
	CON_RX_PARAM_DATA_VPT_VALUE,//0x09
	CON_RX_PARAM_DATA_TMP_VALUE,//0x0A
	CON_RX_PARAM_DATA_COND_VALUE,//0B
	CON_RX_PARAM_DATA_UF_RATE,//0C
	CON_RX_PARAM_DATA_UF_GOAL,//0D,
	CON_RX_PARAM_DATA_BOLUS_VOLUME,//0E
	CON_RX_PARAM_DATA_ABF_RATE,//0x0F
	CON_RX_PARAM_DATA_SYSTEM_DATA,//0x10
	CON_RX_PARAM_SYS_SOFT_VERSION, // 0x11
	CON_RX_PARAM_DATA_TREATMENT_DATA, //0x12
	CON_RX_PARAM_DATA_DIALYSIS_FLOW_CONFIG,//0x13
	CON_RX_PARAM_DATA_DIALYSIS_TEMP_CONFIG,//0x14
	CON_RX_PARAM_DATA_HEPARIN_RATE_CONFIG,//0x15
	CON_RX_PARAM_DATA_APT_VALUE_CONFIG,//0x16
	CON_RX_PARAM_DATA_VPT_VALUE_CONFIG,//0x17
	CON_RX_PARAM_DATA_TMP_VALUE_CONFIG,//0x18
	CON_RX_PARAM_DATA_COND_VALUE_CONFIG,//0x19
	CON_RX_PARAM_DATA_UF_RATE_CONFIG,//0x1A
	CON_RX_PARAM_DATA_UF_GOAL_CONFIG,//0x1B,
	CON_RX_PARAM_DATA_BOLUS_VOLUME_CONFIG,//1C
	CON_RX_PARAM_DATA_ABF_RATE_CONFIG,//0X1D
	CON_RX_PARAM_DATA_MIXING_STATUS,//0x1E
	CON_RX_PARAM_DATA_RETRANS_STATUS,//0x1F
	CON_RX_PARAM_DATA_RECIRC_STATUS,//0x20
	CON_RX_PARAM_DATA_DISINF_STATUS,//0x21
	
	
	CON_RX_PARAM_DATA_MAX//0x22
	
}Cl_ConsoleRxDataType;


typedef  enum
{
	ID_dflow = 5,
	ID_settemp = 6,
	ID_heprate = 7,
	ID_apt = 8,
	ID_vpt = 9,
	ID_tmp = 10,
	ID_setcond = 11,
	ID_ufrate = 12,
	ID_ufgoal = 13,
	ID_bolusvol = 14,
	ID_bloodrate = 15,
	ID_bicarbcond = 16,
	ID_hepstoptime = 17,
	ID_syringetype = 18,
	ID_heparincheck = 19,
	ID_minufrate = 20,
	ID_treattime = 21,
	ID_bloodratereturn = 22,
	ID_bloodratetreat = 23,
	ID_tempulimit = 24,
	ID_templlimit = 25,
	ID_tmpllimit = 26,
	ID_tmpulimit = 27,
	ID_vptllimit = 28,
	ID_vptulimit = 29,
	ID_ufllimit = 30,
	ID_ufulimit = 31,
	ID_dflowllimit = 32,
	ID_dflowulimit = 33,
	ID_condllimit = 34,
	ID_condulimit = 35,
	ID_aptllimit = 36,
	ID_aptulimit = 37,
	ID_b_Dlaystedata = 38,
	ID_b_TempData = 39,
	ID_b_Conddata =41,
	ID_b_tmp = 42,
	ID_b_apt =43,
	ID_b_vpt = 44,
	ID_b_treatmentdata = 45,
	ID_MAX_TREAT_PARAM

}Cl_ConsoleRxTreatDataValType;
				
typedef enum {
	CON_TX_PARAM_DATA_NULL, //0
	CON_TX_PARAM_DATA_RINSE_STATUS,//1
	CON_TX_PARAM_DATA_PRIME_STATUS,//2
	CON_TX_PARAM_DATA_DIALYSER_PRIME_STATUS,//3
	CON_TX_PARAM_DATA_DIALYSIS_STATUS, //4
	CON_TX_PARAM_DATA_DIALYSIS_FLOW,//5
	CON_TX_PARAM_DATA_DIALYSIS_TEMP,//6
	CON_TX_PARAM_DATA_HEPARIN_RATE,//7
	CON_TX_PARAM_DATA_APT_VALUE,//8
	CON_TX_PARAM_DATA_VPT_VALUE,//9
	CON_TX_PARAM_DATA_TMP_VALUE,//A
	CON_TX_PARAM_DATA_COND_VALUE,//0B
	CON_TX_PARAM_DATA_UF_RATE,//0C
	CON_TX_PARAM_DATA_UF_GOAL,//0D,
	CON_TX_PARAM_DATA_BOLUS_VOLUME,//0E
	CON_TX_PARAM_DATA_ABF_RATE,//0x1F
	CON_TX_PARAM_DATA_SYSTEM_DATA,//0x10
	CON_TX_PARAM_SYS_SOFT_VERSION, // 0x11
	CON_TX_PARAM_DATA_TREATMENT_DATA, //0x12
	CON_TX_PARAM_DATA_DIALYSIS_FLOW_CONFIG,//0x13
	CON_TX_PARAM_DATA_DIALYSIS_TEMP_CONFIG,//0x14
	CON_TX_PARAM_DATA_HEPARIN_RATE_CONFIG,//0x15
	CON_TX_PARAM_DATA_APT_VALUE_CONFIG,//0x16
	CON_TX_PARAM_DATA_VPT_VALUE_CONFIG,//0x17
	CON_TX_PARAM_DATA_TMP_VALUE_CONFIG,//0x18
	CON_TX_PARAM_DATA_COND_VALUE_CONFIG,//0x19
	CON_TX_PARAM_DATA_UF_RATE_CONFIG,//0x1A
	CON_TX_PARAM_DATA_UF_GOAL_CONFIG,//0x1B,
	CON_TX_PARAM_DATA_BOLUS_VOLUME_CONFIG,//1C
	CON_TX_PARAM_DATA_ABF_RATE_CONFIG,//0x1D
	CON_TX_PARAM_DATA_UF_RPM,//0x1E // testing
	CON_TX_PARAM_DATA_UF_HR_RPM,//0x1F //testing
	CON_TX_PARAM_DATA_MIXING,//0x20
	CON_TX_PARAM_DATA_RCIRC,//0x21
	CON_TX_PARAM_DATA_RETRANS,//0x22
	CON_TX_PARAM_DATA_DISINF_STATUS,//0x23
	CON_TX_PARAM_DATA_PRESSURE_DATA, //0x1E
	
	CON_TX_PARAM_DATA_MAX		 //0x1F
	}Cl_ConsoleTxDataType;


typedef enum {
	COMMAND_RESULT_FAILURE,
	COMMAND_RESULT_SUCCESS,
	COMMAND_RESULT_OTHER
	}Cl_ConsoleTxConfirmType;
	


typedef enum {
	REASON1,
	REASON2,
	REASON3,
} Cl_ConsoleTxfailureReasonType;

typedef enum
{
	

	STANDBY = 0,
	CLEANING,
	POST_CLEAN_STANDBY,
	FILLING,
	PRIMING,
	POST_PRIMING_STANDBY,
	DIALYSER_PRIMING,
	POST_PREPARATION_STANDBY,
	POST_PATIENT_CONNECTED,
	DIALYSIS,
	POST_DIALYSIS
}Cl_Console_SystemStatetype;


typedef enum
{
	
	CLEAN_IDLE,
	CLEAN_CLEANING,
	CLEAN_CLEAN_ALARM_STOPPED,
	CLEAN_CLEAN_STOPPED,
}Cl_Console_RinseSubstatetype;

typedef enum
{
	
	PRIME_IDLE,
	PRIME_PRIMING,
	PRIME_PRIME_STOPPED,
}Cl_Console_PrimeSubstatetype;

typedef enum
{
	
	DIALYSIS_IDLE,
	DIALYSISDIALYSIS,
	DIALYSISDIALYSIS_STOPPED,
}Cl_Console_DialysisSubstatetype;

typedef enum
{
	
	RETRANS_IDLE,
	RETRANS_RETRANS,
	RETRANS_RETRANS_STOPPED,
}Cl_Console_RetransSubstatetype;

	typedef enum
	{
		

		STANDBY_DATA = 0,
		CLEAN_DATA,
		PRIMING_DATA,
		DIALYSER_PRIME_DATA,
		DIALYSIS_PREP_DATA,
		DIALYSIS_DATA,
		TREATMENT_DATA,
		RECIRC_DATA,
		DUMMY_8,
		DUMMY_9,
		RETURN_STATE,
		DISINF_STATE,

	}Cl_Console_bulkdatatype;
	
	
	typedef struct
	{
		int commands_inouttype;
		int command;
		
	}command_type;
	
	typedef struct  
	{
		command_type cmdtype[100];
		int array_commands_index;
	}array_command_type;

#endif /* CL_CONSOLEHANDLER_H_ */
