/*
 * cl_heparinfeedback.h
 *
 * Created: 11/6/2014 9:05:24 AM
 *  Author: user
 */ 


#ifndef CL_HEPARINFEEDBACK_H_
#define CL_HEPARINFEEDBACK_H_

typedef enum {
	
	CL_HEP_P_STATE_IDLE,
	CL_HEP_P_STATE_READY_AT_START,
	CL_HEP_P_STATE_STOPPED_AT_END,
	CL_HEP_P_STATE_STARTED,
	CL_HEP_P_STATE_RUNNING,
	CL_HEP_P_STATE_RUNNING_NORMAL,
	CL_HEP_P_STATE_RUNNING_SLOW,
	CL_HEP_P_STATE_RUNNING_FAST,
	CL_HEP_P_STATE_RETRACTING,
	CL_HEP_P_STATE_STOPPED,
	CL_HEP_P_STATE_PAUSED,
	CL_HEP_P_STATE_COMPLETED,
	CL_HEP_P_STATE_MAXSTATE
	
}cl_hep_pump_states;




#endif /* CL_HEPARINFEEDBACK_H_ */