/*
 * sv_types.h
 *
 * Created: 1/13/2014 9:40:57 AM
 *  Author: user
 */ 


#ifndef SV_TYPES_H_
#define SV_TYPES_H_


typedef enum
{
	SV_OK,
	SV_WAIT,
	SV_ACCEPTED,
	SV_REJECTED,
	SV_FAIL
	
}Sv_ReturnCodesType;




typedef enum{
	NV_NVM_NODATA, //0
	NV_NVM_RINSE_STATUS,//1
	NV_NVM_PRIME_STATUS,//2
	NV_NVM_DIALYSER_PRIME_STATUS,//3
	NV_NVM_DIALYSIS_STATUS,//4_
	NV_DIALYSATE_FLOW,//5
	NV_DIALYSATE_TEMP,//6
	NV_APT_VALUE,//7
	NV_VPT_VALUE,//8
	NV_TMP,//9
	NV_CONDUCTIVITY,//10
	NV_UF_REMOVAL_RATE,//11
	NV_UF_GOAL,//12
	NV_ARTERIAL_BLOODFLOW_RATE,//13
	NV_HEPARIN_FLOW_RATE,//14
	NV_HEPARIN_BOLUS,//15
	NV_ABD_THRESHOLD,//16
	NV_BLD_THRESHOLD,//17
	NV_DIALYSIS_FLOW_CONFIG_UPPER,//18
	NV_DIALYSIS_FLOW_CONFIG_LOWER,//19
	NV_DIALYSIS_TEMP_CONFIG_UPPER,//20
	NV_DIALYSIS_TEMP_CONFIG_LOWER,//21
	NV_HEPARIN_RATE_CONFIG_UPPER,//22
	NV_HEPARIN_RATE_CONFIG_LOWER,//23
	NV_APT_VALUE_CONFIG_UPPER,//24
	NV_APT_VALUE_CONFIG_LOWER,//25
	NV_VPT_VALUE_CONFIG_UPPER,//26
	NV_VPT_VALUE_CONFIG_LOWER,//27
	NV_TMP_VALUE_CONFIG_UPPER,//28
	NV_TMP_VALUE_CONFIG_LOWER,//29
	NV_COND_VALUE_CONFIG_UPPER,//30
	NV_COND_VALUE_CONFIG_LOWER,//31
	NV_UF_RATE_CONFIG_UPPER,//32
	NV_UF_RATE_CONFIG_LOWER,//33
	NV_UF_GOAL_CONFIG_UPPER,//34
	NV_UF_GOAL_CONFIG_LOWER,//35
	NV_BOLUS_VOLUME_CONFIG_UPPER,//36
	NV_BOLUS_VOLUME_CONFIG_LOWER,//37
	NV_ABF_RATE_CONFIG_UPPER,//38
	NV_ABF_RATE_CONFIG_LOWER,//39
	NV_NVM_DISINF_STATUS,//40
	NV_NVM_MAXDATA//41
}sv_nvm_dataidtype;




#endif /* SV_TYPES_H_ */