/*
 * IncFile1.h
 *
 * Created: 11/6/2014 9:07:58 AM
 *  Author: user
 */ 


#ifndef INCFILE1_H_
#define INCFILE1_H_

typedef enum {
	
	CL_BP_P_STATE_IDLE,
	CL_BP_P_STATE_STARTED,
	CL_BP_P_STATE_RUNNING,
	CL_BP_P_STATE_RUNNING_NORMAL,
	CL_BP_P_STATE_RUNNING_SLOW,
	CL_BP_P_STATE_RUNNING_FAST,
	CL_BP_P_STATE_STOPPED,
	CL_BP_P_STATE_PAUSED,
	CL_BP_P_STATE_COMPLETED,
	CL_BP_P_STATE_MAXSTATE
	
}cl_bp_pump_states;




#endif /* INCFILE1_H_ */