/*
 * cl_init.h
 *
 * Created: 3/24/2014 12:41:55 PM
 *  Author: user
 */ 


#ifndef CL_INIT_H_
#define CL_INIT_H_



typedef enum
{
	EVENT_NULL_EVENT,
	EVENT_INIT_INIT,
	EVENT_INIT_TICK_100MS,
	EVENT_INIT_TICK_500MS,
	EVENT_INIT_TICK_SECOND,
	EVENT_INIT_TICK_MINUTE,
	EVENT_INIT_TICK_HOUR,
	EVENT_INIT_MAXEVENT
}Cl_Init_Events;


typedef enum
{
	CL_INIT_STATE_IDLE,
	CL_INIT_STATE_INIT,
	CL_INIT_ROM_TEST_ON,
	CL_INIT_ROM_TEST_DONE,
	CL_INIT_ROM_TEST_PASSED,
	CL_INIT_RAM_TEST_ON,
	CL_INIT_RAM_TEST_DONE,
	CL_INIT_RAM_TEST_PASSED,
	CL_INIT_READY,
	CL_INIT_STATE_MAXSTATE
} Cl_Init_StatesType;



#endif /* CL_INIT_H_ */